//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeLi.PdfSign.App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeLi.PdfSign.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 位置超出水平方向范围 的本地化字符串。
        /// </summary>
        internal static string BeyondHView {
            get {
                return ResourceManager.GetString("BeyondHView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置超出垂直方向范围 的本地化字符串。
        /// </summary>
        internal static string BeyondVView {
            get {
                return ResourceManager.GetString("BeyondVView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部二维码 的本地化字符串。
        /// </summary>
        internal static string BottomCode {
            get {
                return ResourceManager.GetString("BottomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DrawingReview {
            get {
                object obj = ResourceManager.GetObject("DrawingReview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 图纸审核专用章 的本地化字符串。
        /// </summary>
        internal static string DrawingReviewSign {
            get {
                return ResourceManager.GetString("DrawingReviewSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF文件(*.pdf)|*.pdf 的本地化字符串。
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GeneralOffice {
            get {
                object obj = ResourceManager.GetObject("GeneralOffice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 总工室审图章 的本地化字符串。
        /// </summary>
        internal static string GeneralOfficeSign {
            get {
                return ResourceManager.GetString("GeneralOfficeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImgTag 的本地化字符串。
        /// </summary>
        internal static string ImgTag {
            get {
                return ResourceManager.GetString("ImgTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否保存？ 的本地化字符串。
        /// </summary>
        internal static string IsSave {
            get {
                return ResourceManager.GetString("IsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置水平方向不可见 的本地化字符串。
        /// </summary>
        internal static string LoseHView {
            get {
                return ResourceManager.GetString("LoseHView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置超出垂直方向范围 的本地化字符串。
        /// </summary>
        internal static string LoseVView {
            get {
                return ResourceManager.GetString("LoseVView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QrCode {
            get {
                object obj = ResourceManager.GetObject("QrCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择PDF文件 的本地化字符串。
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图签失败 的本地化字符串。
        /// </summary>
        internal static string SignError {
            get {
                return ResourceManager.GetString("SignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部二维码 的本地化字符串。
        /// </summary>
        internal static string TopCode {
            get {
                return ResourceManager.GetString("TopCode", resourceCulture);
            }
        }
    }
}
